#spring.datasource.url=jdbc:h2:mem:addressbook_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.h2.console.enabled=true

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:addressbook_db
    username: sa
    password:
    driverClassName: org.h2.Driver

#server:
#  port: 9896